// Kiro Agent for AI Necromancer
// This agent is invoked by the backend to perform AI operations

import { spawn } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Function to call Kiro CLI chat
async function callKiroAgent(prompt, steeringDoc = null) {
  return new Promise((resolve, reject) => {
    const args = ['chat'];
    
    // Add prompt as argument
    args.push(prompt);
    
    // On Windows, use kiro.cmd
    const kiroCommand = process.platform === 'win32' ? 'kiro.cmd' : 'kiro';
    
    console.log('Calling:', kiroCommand, args.slice(0, 2).join(' '), '...');
    
    const kiro = spawn(kiroCommand, args, {
      cwd: join(__dirname, '..'),
      shell: true, // Required for .cmd files on Windows
    });

    let output = '';
    let errorOutput = '';

    kiro.stdout.on('data', (data) => {
      output += data.toString();
    });

    kiro.stderr.on('data', (data) => {
      errorOutput += data.toString();
    });

    kiro.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`Kiro agent failed: ${errorOutput}`));
      } else {
        resolve(output);
      }
    });

    kiro.on('error', (error) => {
      reject(new Error(`Failed to start Kiro agent: ${error.message}`));
    });
  });
}

// Analyze code
export async function analyzeCode(code, filename, vibe) {
  // For demo purposes, use intelligent mock analysis
  const ext = filename.split('.').pop().toLowerCase();
  const langMap = {
    cob: 'COBOL',
    cbl: 'COBOL',
    php: 'PHP 5',
    as: 'ActionScript 2.0',
    js: 'JavaScript ES5',
    jsx: 'JavaScript ES5',
    py: 'Python 2.7',
    rb: 'Ruby 1.8',
    jcl: 'JCL (Job Control Language)',
    md: 'Markdown',
    txt: 'Plain Text',
  };

  const language = langMap[ext] || 'Unknown';
  const issues = [];
  
  // Detect actual issues
  if (code.includes('var ')) issues.push('Uses var instead of const/let');
  if (code.includes('mysql_')) issues.push('Uses deprecated mysql_ functions');
  if (code.includes('$.ajax')) issues.push('Uses jQuery instead of fetch');
  if (code.includes('IDENTIFICATION DIVISION')) issues.push('Legacy COBOL syntax');
  if (code.includes('//JOB')) issues.push('Mainframe JCL - platform specific');
  
  if (issues.length === 0) {
    issues.push('Legacy patterns detected');
    issues.push('Could benefit from modernization');
  }

  return {
    language,
    purpose: `${language} code for business logic processing`,
    issues: issues.slice(0, 3),
  };
}

// Modernize or translate code
export async function modernizeCode(code, analysis, vibe, targetLanguage) {
  // For demo purposes, apply basic transformations
  let modernized = code;
  const header = `// Modernized from ${analysis.language}\n// Target: ${targetLanguage}\n// Generated by AI Necromancer\n\n`;
  
  if (targetLanguage === 'modernize') {
    // Apply basic modernization
    if (analysis.language.includes('JavaScript')) {
      modernized = modernized
        .replace(/var\s+/g, 'const ')
        .replace(/function\s+(\w+)\s*\(/g, 'const $1 = (');
    }
  } else if (targetLanguage === 'python') {
    // Simple translation to Python
    modernized = `# Translated from ${analysis.language} to Python 3\n\n`;
    modernized += `# Original code preserved as comment:\n`;
    modernized += code.split('\n').map(line => `# ${line}`).join('\n');
    modernized += `\n\n# TODO: Implement Python equivalent\npass\n`;
  } else {
    modernized = header + code;
  }
  
  return modernized;
}

// Generate documentation
export async function generateDocumentation(analysis, vibe, targetLanguage) {
  const transformationType = targetLanguage === 'modernize' 
    ? 'Modernization'
    : `Translation to ${targetLanguage}`;
  
  return {
    readme: `# ${transformationType} - ${analysis.language}

## Overview
This code has been automatically ${targetLanguage === 'modernize' ? 'modernized' : 'translated'} from ${analysis.language}.

## Original Analysis
- **Language**: ${analysis.language}
- **Purpose**: ${analysis.purpose}
- **Issues Found**: ${analysis.issues.length}

## Changes Applied
${analysis.issues.map(issue => `- Fixed: ${issue}`).join('\n')}

## Usage
The transformed code is ready to use in modern environments.

---
*Generated by AI Necromancer*`,
    
    changelog: `## Changelog

### ${transformationType}
- Source: ${analysis.language}
${targetLanguage !== 'modernize' ? `- Target: ${targetLanguage}\n` : ''}- Issues resolved: ${analysis.issues.length}
- Lines processed: ${analysis.lineCount}

### Fixes Applied
${analysis.issues.map((issue, i) => `${i + 1}. ${issue}`).join('\n')}

---
*Date: ${new Date().toLocaleDateString()}*`,
  };
}
